### ISSUE TITLE
Error when running webpack

### ISSUE THREAD

**Issue by chollier** [gurdasnijor/component-flow-loader#4]
When installing component-flow-loader and adding "component-flow" to my loaders, I get the following error when running webpack : 

```

ERROR in ./~/component-flow-loader/~/css-loader!./~/component-flow-loader/~/sass-loader!./~/component-flow-loader/~/autoprefixer-loader!./~/component-flow-loader/runtime_components/style.scss
Module build failed: CssSyntaxError: /Users/loic/nervecenter/node_modules/component-flow-loader/runtime_components/style.scss:144:1: Unknown word
////////////////////////////////////////////////////////////////////////////////
// 3D CONTROLS
^
////////////////////////////////////////////////////////////////////////////////
  at Input.error (/Users/loic/nervecenter/node_modules/component-flow-loader/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/input.js:56:21)
  at Parser.unknownWord (/Users/loic/nervecenter/node_modules/component-flow-loader/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/parser.js:352:30)
  at Parser.decl (/Users/loic/nervecenter/node_modules/component-flow-loader/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/parser.js:219:22)
  at Parser.word (/Users/loic/nervecenter/node_modules/component-flow-loader/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/parser.js:129:30)
  at Parser.loop (/Users/loic/nervecenter/node_modules/component-flow-loader/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/parser.js:46:26)
  at Function.module.exports [as parse] (/Users/loic/nervecenter/node_modules/component-flow-loader/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/parse.js:11:12)
  at PostCSS.process (/Users/loic/nervecenter/node_modules/component-flow-loader/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/postcss.js:43:30)
  at Autoprefixer.process (/Users/loic/nervecenter/node_modules/component-flow-loader/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/lib/autoprefixer.js:57:36)
  at Object.module.exports (/Users/loic/nervecenter/node_modules/component-flow-loader/node_modules/autoprefixer-loader/index.js:42:42)
 @ ./~/component-flow-loader/~/style-loader!./~/component-flow-loader/~/css-loader!./~/component-flow-loader/~/sass-loader!./~/component-flow-loader/~/autoprefixer-loader!./~/component-flow-loader/runtime_components/style.scss 4:14-401
```

My webpack version is `Version: webpack 1.4.13`

**Comment by gurdasnijor** [comment]
Thanks for reporting this; can you paste your webpack config?

**Comment by dev-mraj** [comment]
same+
```
module.exports = {

    server:{
        publicPath: "/dist/",
        port: 8542,
        keepalive:true,
        debug   : true,
        watch: true,
        progress: true,
    },

    keepalive:true,

    entry: {
        backend: __dirname+"/js/backend/index.js",
        frontend: __dirname+"/js/frontend/index.js",
    },
    output: {
        // Make sure to use [name] or [id] in output.filename
        //  when using multiple entry points
        path: __dirname+"/../dist/",
        publicPath:'/dist/',
        filename: "[name].bundle.js",
        chunkFilename: "[id].bundle.js"
    },

    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "windows.jQuery": "jquery"
        }),
       // new webpack.optimize.UglifyJsPlugin(),
       // new webpack.optimize.OccurenceOrderPlugin(),
    ],
    resolve:{
        alias: {
            //'jquery.nicescroll': './libs/jquery.nicescroll',
            sizzle: __dirname+'../../../bower_components/sizzle/dist/sizzle.js',
            jquery: __dirname+'../../../bower_components/jquery/src/jquery.js',
            knockout: __dirname+'../../../bower_components/knockout/dist/knockout.debug',
            socketio: __dirname+'../../../node_modules/socket.io-client/index',
            cookies: __dirname+'../../../bower_components/cookies-js/dist/cookies',
           // underscore: 'bower_components/underscore/underscore',
           // backbone: 'bower_components/backbone/backbone',
            //moment: 'bower_components/moment/moment'
        }
    },


    devtool : 'source-map',
    optimize : {
//      minimize : true,
    },
    colors:true,
    module: {
        loaders: [
            /*{
                test: /\.html$/,
                loader: 'html?attrs=link:href'
            },*/
            {
                test: /\.css$/,
                loader: "style-loader!css-loader"
            },
            {
                test: /\.png$/,
                loader: "url-loader?limit=100000"
            },
            {
                test: /\.jpg$/,
                loader: "file-loader"
            },
            {
                test: /\.js?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel'
            },
            {
                test: /\.json?$/,
                loader: 'json'
            },
            /*{
                test: /\.css$/,
                loader: 'style!css?modules&localIdentName=[name]---[local]---[hash:base64:5]'
            }*/
        ]
    }
};
```
